run_time_utc: "05:30"   # kdy má akce běžet (UTC)
universe:
  portfolio:
    - GOOGL
    - ABEA.DE
    - MU
    - VKTX
    - PK
    - BRZE
    - VALE
    - PBR
    - PBR-A
    - RHM.DE
    - HAG.DE
    - TKA.DE
    - SAAB-B.ST
    - BA.L
    - LDO.MI
    - KOMB.PR
    - CZG.PR
    - CEZ.PR
    - ASML
    - NVO
    - ACLS
    - MDLZ
    - KO
    - EXAS
    - CIVI
    - LPG
    - IMVT
    - FIVN
    - ANGI
    - OXSQ
    - MSFT
    
  watchlist:
    universe:
  watchlist:
    - "NVDA"
    - "AMD"
    - "AVGO"
    - "LRCX"
    - "KLAC"
    - "TSM"
    - "LMT"
    - "NOC"
    - "RTX"
    - "GD"
    - "MSFT"
    - "ADBE"
    - "ORCL"
    - "CRM"
    - "COST"
    - "WMT"
    - "PG"
    - "PEP"
    - "LLY"
    - "TMO"
    - "SYK"
    - "LIN"
    - "HON"
    - "CAT"
    - "XOM"
    - "CVX"
    - "COP"
    - "SLB"
    - "AIR.PA"
    - "PLTR"
    - "NOW"
    - "AXP"
    - "GS"
    - "C"
    - "CPB"
    - "STZ"
    - "BMY"
    - "META"
    - "CLX"
    - "PYPL"
    - "ABNB"
    - "CRWD"
    - "MELI"
    - "ISRG"
    - "SHOP"
    - "AMZN"
    - "YUMC"
    - "BABA"
    - "BIDU"
    - "TCEHY"
    - "JD"
    - "GSK"
    
limits:
  max_weight_per_ticker: 0.07
  max_weight_defense: 0.20
  max_weight_commodities_latam: 0.08
  max_weight_biotech: 0.03

watchlist_rules:
  min_history_days: 252
  needs_close_above_sma50: true
  needs_close_above_sma200: true
  rsi_min: 45
  rsi_max: 65
  min_dist_from_52w_high: 0.05
  min_vol_ratio_20d: 1.2
  earnings_blackout_days: 1
  confirm_days: 3

# ---------- GURU MIX ----------
# váhy jednotlivých přístupů; používá se vážený průměr -> jeden sloupec "Guru-mix"
guru_mix_weights:
  buffett: 25
  graham: 20
  greenblatt: 15
  raschke: 10
  lynch: 15
  icahn: 7.5
  ackman: 7.5

# Monotónní mapování Guru-mix -> signál
# (používá ho kód: AVOID < HOLD < BUY < BUY+ < BUY++)
signal_thresholds:
  strong_buy: 20   # BUY++
  buy: 12          # BUY+
  hold: 6          # BUY
# pokud 0 < mix < hold => HOLD, jinak AVOID

# ---------- TRIM PRAVIDLA ----------
trim_rules:
  # A) přehřátý moment (profit-taking)
  momentum_1:
    rsi_min: 70
    sma50_premium_min: 0.15   # cena alespoň 15 % nad SMA50
    trim_fraction: 0.25
  momentum_2:
    rsi_min: 75
    sma50_premium_min: 0.20
    trim_fraction: 0.33

  # B) profit lock-in
  profit_1:
    gain_min: 0.30            # zisk na pozici ≥ 30 %
    rsi_min: 65
    trim_fraction: 0.25
  profit_2:
    gain_min: 0.50
    rsi_min: 70
    trim_fraction: 0.50

  # C) zhoršení kvality (mix/signál)
  quality_drop:
    drop_pct_min: 0.30        # pokles vs 20D průměr Guru-mixu ≥ 30 %
    min_gain: 0.10
    trim_fraction: 0.25
  double_downgrade:
    trim_fraction: 0.33       # např. BUY++ → BUY během krátké doby

  # D) koncentrace/riziko
  weight_cap:
    max_weight: 0.10          # udrž váhu pod 10 %; nadbytek se trimuje

# ---------- ALOKACE A RIZIKO ----------
allocation:
  mode: equal_weight
  target_weight: 0.05
  max_pos_weight: 0.12
  min_pos_weight: 0.01
  max_positions: 30
  cash_buffer: 0.10
  sector_caps:
    Defense: 0.35
    Tech: 0.45
    Materials: 0.30
    Energy: 0.30
    Financials: 0.30
    Healthcare: 0.35
    RealEstate: 0.25
    Utilities: 0.30
    Industrials: 0.35
    Consumer: 0.35
  sector_by_ticker:
    GOOGL: Tech
    ABEA.DE: Tech
    MU: Tech
    BRZE: Tech
    ACLS: Tech
    EXAS: Healthcare
    IMVT: Healthcare
    FIVN: Tech
    VKTX: Healthcare
    RHM.DE: Defense
    HAG.DE: Defense
    SAAB-B.ST: Defense
    LDO.MI: Defense
    CZG.PR: Defense
    BA.L: Defense
    TKA.DE: Industrials
    KOMB.PR: Financials
    PK: RealEstate
    VALE: Materials
    PBR: Energy
    PBR-A: Energy
    CEZ.PR: Utilities
    KO: Consumer
    MDLZ: Consumer
    LPG: Energy
    NVO: Healthcare
    ASML: Tech

risk:
  capital_total: 25000
  risk_per_trade: 0.01
  hard_stop_pct: 0.20
  trailing_atr_mult: 3.0
  take_profit_ladders:
    - { gain_pct: 0.15, trim_pct: 0.15 }
    - { gain_pct: 0.25, trim_pct: 0.10 }
    - { gain_pct: 0.40, trim_pct: 0.10 }

rebalance:
  frequency: weekly
  drift_band: 0.25
  min_trade_value: 100
  min_trade_pct: 0.005

# Volitelná technická „brzda“ pro exekuci vstupu (nad rámec samotného signálu z mixu)
entry_filters:
  require_close_above_sma50: true
  rsi_max: 70
  distance_52w_high_max: 0.15
  cooldown_days: 3
  dip_buy_levels: [-0.05, -0.10, -0.15]

sell_rules:
  close_below_sma50_days: 5
  stop_loss_pct: 0.20

execution:
  lot_size: 1
